// src/main/java/com/example/orderservice/dto/OrderItemCreationRequest.java
package org.example.usermanagment;

import java.math.BigDecimal;

public class OrderItemCreationRequest {
    private String orderId; // The UUID generated by the Order Service
    private String dishId;   // String representation of dish ID
    private int quantity;
    private BigDecimal price;

    public OrderItemCreationRequest() {}

    public OrderItemCreationRequest(String orderId, String dishId, int quantity, BigDecimal price) {
        this.orderId = orderId;
        this.dishId = dishId;
        this.quantity = quantity;
        this.price = price;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getDishId() {
        return dishId;
    }

    public void setDishId(String dishId) {
        this.dishId = dishId;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}